"""
Growth reporter — detects gaps in the voice library and writes reports.

Three triggers:
  1. no_match_routing   — SPIRAL UP fell back to default; nothing genuinely fit
  2. failed_landing     — RETURN couldn't land after retry; library didn't have what was needed
  3. unknown_configuration — compound emotions detected but no named pattern matched

Reports write to reports/growth/ as timestamped markdown.
Draft Fort Kit skeletons write to voices_pending/ for human review.
allow_self_extension in manifest.json gates auto-promotion (currently false).
"""
import json
import re
from datetime import datetime
from pathlib import Path
from core.state import EmotionalSignature, RouteDecision, IntegrationFeedback
from core import llm

REPORTS_DIR = Path(__file__).parent.parent / "reports" / "growth"
PENDING_DIR = Path(__file__).parent.parent / "voices_pending"

DRAFT_SYSTEM = """You are a voice architect for the F.I.N.E. system. Output ONLY raw JSON. No explanation. No markdown. No preamble.

Given a gap analysis, draft a minimal Fort Kit v2.0 voice skeleton for a voice that would cover this missing territory.

OUTPUT FORMAT — exactly this structure, fill in the [...] placeholders:
{
  "metadata": {"id": "...-001", "version": "2.0.0", "spineType": "voice", "family": "...Craft", "status": "draft"},
  "identity": {"voiceName": "...", "descriptiveTagline": "...", "characterEssence": "..."},
  "domain": {"primaryHome": "...", "containmentZone": "2"},
  "narrativeRole": {"uniquePurpose": "...", "invocationPhrase": "..."},
  "territory": "...",
  "reachable_from": ["..."],
  "not_from": ["..."],
  "system_prompt": "You are [VoiceName]. ...",
  "growth_note": "DRAFT — generated by growth reporter. Requires human review before promotion."
}"""


def _detect_trigger(
    route: RouteDecision,
    signature: EmotionalSignature,
    integration: IntegrationFeedback,
) -> tuple[bool, str]:
    # Trigger 1: SPIRAL UP fell back to default with no genuine match
    if route.primary_voice == "DeepCurrent" and route.reasoning:
        fallback_signals = ["closest", "no voice", "fallback", "default", "none match", "approximate"]
        if any(s in route.reasoning.lower() for s in fallback_signals):
            return True, "no_match_routing"

    # Trigger 2: Failed landing after retry exhausted (next_signature is None = no retry left)
    if not integration.landed and integration.next_signature is None:
        return True, "failed_landing"

    # Trigger 3: Compound emotions present but no configuration recognized
    if signature.compound_emotions and not signature.configuration:
        return True, "unknown_configuration"

    return False, None


def _draft_voice_skeleton(trigger: str, signature: EmotionalSignature, route: RouteDecision) -> dict | None:
    compound_desc = ""
    if signature.compound_emotions:
        parts = [f"{c.emotion}({c.role}, intensity {c.intensity})" for c in signature.compound_emotions]
        compound_desc = f"Compound: {', '.join(parts)}"

    prompt = f"""Gap analysis:
Trigger: {trigger}
Input: {signature.raw_input[:200]}
Color: {signature.color} | Intensity: {signature.intensity} | Tags: {', '.join(signature.tags)}
{compound_desc}
Route attempted: {route.primary_voice} — {route.reasoning}

Draft a Fort Kit voice skeleton for the voice that should have handled this."""

    try:
        result = llm.decide(DRAFT_SYSTEM, prompt)
        result = result.strip()
        match = re.search(r'\{.*\}', result, re.DOTALL)
        if match:
            return json.loads(match.group())
    except Exception:
        pass
    return None


def _write_report(trigger: str, signature: EmotionalSignature, route: RouteDecision,
                  integration: IntegrationFeedback, draft: dict | None) -> Path:
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    report_path = REPORTS_DIR / f"growth_{trigger}_{timestamp}.md"

    compound_section = ""
    if signature.compound_emotions:
        lines = [f"- {c.emotion}: {c.color}, intensity {c.intensity}, role: {c.role}"
                 for c in signature.compound_emotions]
        compound_section = "\n**Compound emotions:**\n" + "\n".join(lines)

    draft_section = ""
    if draft:
        draft_section = f"\n## Draft Voice Skeleton\n\n```json\n{json.dumps(draft, indent=2)}\n```\n"
        draft_section += "\n_Review this skeleton. If it covers real missing territory, move it to `assets/voices/` and give it a full Fort Kit treatment._\n"

    report = f"""# Growth Report — {trigger.replace('_', ' ').title()}

**Timestamp:** {timestamp}
**Trigger:** `{trigger}`

## Input

```
{signature.raw_input}
```

## Emotional Signature

- **Color:** {signature.color}
- **Body location:** {signature.body_location}
- **Intensity:** {signature.intensity}/10
- **Shadow layer:** {signature.shadow_layer or 'none'}
- **Tags:** {', '.join(signature.tags)}
- **Configuration detected:** {signature.configuration or 'none'}{compound_section}

## Route Attempted

- **Primary voice:** {route.primary_voice}
- **Support voices:** {', '.join(route.support_voices) if route.support_voices else 'none'}
- **Reasoning:** {route.reasoning}

## Landing Result

- **Landed:** {integration.landed}
- **Adjustment:** {integration.adjustment or 'none'}

## Gap Analysis

**Trigger reason:** {trigger}

{"The router fell back to the default voice — nothing in the library genuinely covered this territory." if trigger == "no_match_routing" else ""}
{"The output failed to land and the retry loop was exhausted — the library did not have what this input needed." if trigger == "failed_landing" else ""}
{"Compound emotional structure detected but no known configuration matched. This may be a new configuration pattern worth naming." if trigger == "unknown_configuration" else ""}
{draft_section}
---
_Generated by F.I.N.E. growth reporter. Human review required before any voice promotion._
"""

    report_path.write_text(report)
    return report_path


def _save_pending_draft(draft: dict, trigger: str) -> Path | None:
    if not draft:
        return None
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    name = draft.get("identity", {}).get("voiceName", "UnknownVoice")
    path = PENDING_DIR / f"{name}_{trigger}_{timestamp}.json"
    path.write_text(json.dumps(draft, indent=2))
    return path


def check_and_report(
    signature: EmotionalSignature,
    route: RouteDecision,
    integration: IntegrationFeedback,
) -> Path | None:
    """
    Call after RETURN. Returns the report path if a gap was detected, None otherwise.
    """
    triggered, trigger = _detect_trigger(route, signature, integration)
    if not triggered:
        return None

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    PENDING_DIR.mkdir(parents=True, exist_ok=True)

    draft = _draft_voice_skeleton(trigger, signature, route)
    report_path = _write_report(trigger, signature, route, integration, draft)
    _save_pending_draft(draft, trigger)

    return report_path
